[package]
name = "rapidquilt"
version = "0.4.0"
authors = ["Michal Srb <michalsrb@gmail.com>"]
edition = '2018'

[profile.release]
lto = true

[dependencies]
rayon = "1.0"
getopts = "0.2"
failure = "0.1"
seahash = "3.0"
lazy_static = "1.2"
libc = "0.2"
regex = "1"
