[package]
name = "rapidquilt"
version = "0.5.0"
authors = ["Michal Srb <michalsrb@gmail.com>"]
edition = '2018'

[profile.release]
lto = true

[dependencies]
colored = "1"
derive_builder = "0.7"
failure = "0.1"
getopts = "0.2"
atty = "0.2"
libc = "0.2"
memchr = "2"
nom = "4"
rayon = "1"
seahash = "3"

[features]
# Enable this feature to enable benchmarks using the (currently) unstable
# test::Bencher.
bencher = []
